### ISSUE TITLE
Cant get sound to work on macOS big Sur

### ISSUE THREAD

**Issue by aaSchcolnik** [kb24x7/rustyvibes#8]
I installed the CLI via brew, followed the usage instructions writing it like this 
rustyvibes /Users/.../Downloads/Soundpacks/cherrymx-black-abs
which is where the sound files are located, the program started running but no sound is working, the first time I ran it it asked for permissions on accesability I clicked open accesibility preferences but nothing appeared, so i searched for the rustyvibes executable which was found in /usr/local/bin/rustyvibes and I dropped it on the accesibility panel, even then it still didnt work, any ideas on how to get it to work? 
I downloaded MechVibes just to check it out and I enjoy it BUT its really resource intensive

**Comment by aaSchcolnik** [comment]
Would restarting the computer make it work?

**Comment by kb24x7** [comment]
You'll have to enable the accessibility settings for the terminal you are using

**Comment by kb24x7** [comment]
I'm gonna make a GUI for this app soon, so enabling permissions would be much easier

**Comment by aaSchcolnik** [comment]
Ah, there we go, now it started working, while a GUI is great i'd say just leave this step regarding the terminal in the README, now it's working great, thank you for your answer, its working just as good as MechVibes and it's using WAY LESS resources. 
Great job man!

**Comment by kb24x7** [comment]
Glad to hear it :)
I'll update the readme soon.
